clc;
clear;
LOSS1=PGIA(0.9,2.5);
LOSS2=PGIA(0.9,2.0);
LOSS3=PGIA(0.9,1.5);
LOSS4=PGIA(0.9,1.0);
figure;
plot(LOSS1, 'b', 'DisplayName', 'PGIA(0.9,2.5)');
hold on;
plot(LOSS2, 'g', 'DisplayName', 'PGIA(0.9,2.0)');
plot(LOSS3, 'm', 'DisplayName', 'PGIA(0.9,1.5)');
plot(LOSS4, 'r', 'DisplayName', 'PGIA(0.9,1.0)');
xlabel('Iteration');
ylabel('Loss');
title('SGD损失函数历史');
legend show;
grid on;

% LOSS5=PGIA(0.9,2.5);
% LOSS6=PGIA(0.5,2.5);
% LOSS7=PGIA(0.4,2.5);
% LOSS8=PGIA(0.2,2.5);
% figure;
% plot(LOSS5, 'b', 'DisplayName', 'PGIA(0.9,2.5)');
% hold on;
% plot(LOSS6, 'g', 'DisplayName', 'PGIA(0.8,2.5)');
% plot(LOSS7, 'm', 'DisplayName', 'PGIA(0.7,2.5)');
% plot(LOSS8, 'r', 'DisplayName', 'PGIA(0.6,2.5)');
% xlabel('Iteration');
% ylabel('Loss');
% title('SGD损失函数历史');
% legend show;
% grid on;