common_args:
  training_type: "simulation"
  random_seed: 0

data_args:
  dataset: "mnist"
  data_cache_dir: C:\\Capstone_project\\FED_ML\\MNIST
  partition_method: "homo"
  partition_alpha: 0.2

model_args:
  model: "simple_cnn"

train_args:
  federated_optimizer: "HierarchicalFL"
  client_id_list: "[]"
  client_num_in_total: 50
  client_num_per_round: 10
  comm_round: 5
  epochs: 1
  batch_size: 8
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001
  group_method: "average"  # 'random', 'average'
  group_num: 3
  group_comm_round: 1
  lr: 0.03

validation_args:
  frequency_of_the_test: 5

device_args:
  using_gpu: false
  gpu_id: 0

comm_args:
  backend: "sp"

tracking_args:
   # When running on MLOps platform(open.fedml.ai), the default log path is at ~/fedml-client/fedml/logs/ and ~/fedml-server/fedml/logs/
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_entity: fedml-ai
  wandb_project: simulation
  run_name: fedml_torch_hierachicalfl_mnist_lr
  using_mlops: false